version: '3'
services:
  php:
    image: php:7.4-fpm-alpine
    expose:
      - '9000'
    depends_on:
      - database
    volumes:
      - ./:/var/www/html:cached
      - ~/docker/log/php:/var/log
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: php
  web:
    image: nginx:latest
    restart: always
    ports:
        - '80:80'
    depends_on:
        - php
        - database
    volumes:
        - ./:/var/www/html:cached
        - ~/docker/log/nginx:/var/log/nginx
        - ./docker/default.conf:/etc/nginx/conf.d/default.conf
  database:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ~/docker/mysql:/var/lib/
    env_file:
      - ./.env
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
