# See https://symfony.com/doc/current/email/dev_environment.html
#swiftmailer:
#    send all emails to a specific address
#    delivery_addresses: ['me@example.com']
# config/packages/dev/swiftmailer.yaml
swiftmailer:
    delivery_addresses: ['thun.nutvalun@nfq.asia']